"""Define the connexion settings common to all setup."""
from pathlib import Path
import sys

# App
APP_NAME = "pyconsql"

# PATH vars
BASE_DIR = Path(__file__).parent.parent.parent.parent
SPECIFICATION_DIR = BASE_DIR / "openapi"
SPECIFICATION_FILE = SPECIFICATION_DIR / "openapi.yml"
MODELS_FILENAME = BASE_DIR / APP_NAME / "api/models_autogenerated.py"

# Server parameters
PORT = 8000

# Resolver parameters
RESOLVER_MODULE_NAME = f"{APP_NAME}.api.controller"
