"""Define the connexion settings common to all setup."""
from pathlib import Path
import sys

# App
IMPORT_NAME = "pyconsql"

# PATH vars
BASE_DIR = Path(__file__).parent.parent.parent.parent
SPECIFICATION_DIR = Path(sys.prefix) / "etc" / IMPORT_NAME
SPECIFICATION_FILE = "openapi.yml"

# Server parameters.
PORT = 8000

# Resolver parameters.
RESOLVER_MODULE_NAME = f"pyconsql.api.controller"

# Model settings.
MODELS_FILENAME = BASE_DIR / "pyconsql/api/models_autogenerated.py"
